pre-commit:
  parallel: true
  commands:
    format:
      run: bun run format:fix
      stage_fixed: true
    lint:
      glob: "*.{ts,tsx,js}"
      run: bunx oxlint {staged_files}

pre-push:
  commands:
    format:
      run: bun run format:check
    typecheck:
      run: bun run typecheck
    test:
      run: bun run test
    lint:
      run: bun run lint
